import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faChartLine, 
  faUsers, 
  faDollarSign, 
  faChartBar, 
  faCog,
  faSearch,
  faBell,
  faSun,
  faMoon,
  faChevronDown,
  faArrowUp,
  faArrowDown,
  faHome,
  faFileAlt,
  faShoppingCart,
  faEnvelope,
  faCalendar,
  faUserCircle,
  faSignOutAlt,
  faBars,
  faTimes,
  faEye,
  faPercent,
  faBriefcase,
  faBuilding,
  faTrophy,
  faCoffee,
  faChartPie,
  faCogs,
  faMinus,
  faLightbulb,
  faShieldAlt,
  faCalendarAlt,
  faUser,
  faCode,
  faFile,
  faDatabase,
  faCloud,
  faMobile,
  faServer,
  faBook,
  faClipboardCheck,
  // Ícones com nomes verificados:
  faCodeBranch,
  faBagShopping,
  faRightLeft,
  faCaretUp,
  faCaretDown
} from '@fortawesome/free-solid-svg-icons'

import { 
  faBell as farBell,
  faUserCircle as farUserCircle
} from '@fortawesome/free-regular-svg-icons'

// Adicione apenas os ícones que existem
library.add(
  faChartLine,
  faUsers,
  faDollarSign,
  faChartBar,
  faCog,
  faSearch,
  faBell,
  faSun,
  faMoon,
  faChevronDown,
  faArrowUp,
  faArrowDown,
  faHome,
  faFileAlt,
  faShoppingCart,
  faEnvelope,
  faCalendar,
  faUserCircle,
  faSignOutAlt,
  faBars,
  faTimes,
  faEye,
  faPercent,
  faBriefcase,
  faBuilding,
  faTrophy,
  faCoffee,
  faChartPie,
  faCogs,
  faMinus,
  faLightbulb,
  faShieldAlt,
  faCalendarAlt,
  faUser,
  faCode,
  faFile,
  faDatabase,
  faCloud,
  faMobile,
  faServer,
  faBook,
  faClipboardCheck,
  // Ícones que existem nas versões mais recentes
  faCodeBranch,
  faCaretUp,
  faCaretDown,
  // Ícones regulares
  farBell,
  farUserCircle
)

// Export para uso em componentes
export {
  faChartLine,
  faUsers,
  faDollarSign,
  faChartBar,
  faCog,
  faSearch,
  faBell,
  faSun,
  faMoon,
  faChevronDown,
  faArrowUp,
  faArrowDown,
  faHome,
  faFileAlt,
  faShoppingCart,
  faEnvelope,
  faCalendar,
  faUserCircle,
  faSignOutAlt,
  faBars,
  faTimes,
  faEye,
  faPercent,
  faBriefcase,
  faBuilding,
  faTrophy,
  faCoffee,
  faCodeBranch,
  faChartPie,
  faCogs,
  faCaretUp,
  faCaretDown,
  faMinus,
  faLightbulb,
  faShieldAlt,
  faCalendarAlt,
  faUser,
  faCode,
  faFile,
  faDatabase,
  faCloud,
  faMobile,
  faServer,
  faBook,
  faClipboardCheck
}